import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Awatar from "@/components/ui/awatarimg";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row justify-center items-center">


        <Link href="/page1">strona 1</Link>
        <Link href="/page2">strona 2</Link>
        
        <Awatar></Awatar>
        </div>
        {children}
      </body>
    </html>
  );
}
